lm: transformer
lm_conf:
    layer: 16
    head: 8
    att_unit: 512
    unit: 2048
    dropout_rate: 0.1

optim: adam
optim_conf:
    lr: 0.002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

batch_type: numel
batch_bins: 3500000
accum_grad: 4
max_epoch: 15
patience: 3
# 修正這裡：改成單行列表格式，最安全
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
use_amp: true
cudnn_benchmark: true
